apiVersion: apps/v1
kind: Deployment
metadata:
  name: jablonski-vce-app-deployment
  namespace: jablonski
  labels:
    app: jablonski-vce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jablonski-vce-app
  template:
    metadata:
      labels:
        app: jablonski-vce-app
    spec:
      volumes:
      - name: jablonski-vce-app-nfs-volume
        persistentVolumeClaim:
          claimName: jablonski-vce-app-nfs-pvc # name of pvc
      containers:
      - name: jablonski-vce-app-container
        image: ghcr.io/uvarc/vce-app:{{ .Values.version.vceApp }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: jablonski-vce-app-nfs-volume
          mountPath: /project/DSone/jaj4zcf/Videos/write # mount inside of container
        env:
        - name: DBNAME
          value: "xx"
        - name: DBUSER
          value: "xx"
        - name: DBHOST
          value: "somrc-mysql-rds.cuovd4ygikd7.us-east-1.rds.amazonaws.com"
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "1"
            
