apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jablonski-vce-secrets
  namespace: jablonski
spec:
  encryptedData:
    DBPASS: AgC3IZwGJg7dEZEQwSdpr/VVv9Yui3FmYQB7GKkqIt3BARwsdiMPtbZMuiCvOGsU6qIxGg3obxCgBpdDzKteOeOHfJteeTNu9T0/PwzfPnsBBp3uzpoMr+IIMYd79URD7V6KfqCp6GIyFBFh1du+Vxnv2rnZRGbkcUlnhhFIdundlyVCJmFvsZWdJpqZHCdBoBLIZm6ZTyovngrBjFU7vk7Ct6MqzIe0N7YARCJr42VHS6ByNiFLKRX17pRKtjHYK9HhB04q6W+dt5Fr4pR+DoL/27XeYLSgwWCWGTePjABUruD2NEvuxSjF7WANP5ULS1ErAnOUoWQDHZE8soF2uDPCh6gTHXZKSnN9v62jyQ6nbyhLrA2Y+Za9/SHUf/9zO6AdJO/YU+UvRSFJCnLOhX6LddA57JBYhS/86ouqXOfmJMTDQKl5gSbYxfCmBU+GxVooDRk0qANIBnRkJnjCMuaEv7WBvUMRYVU+XdH/W4EMsh+pgYbNl4zUBZFmR9/x4rMVCEMYlmUp/izVDosE4GhaCndHF7PcBn4XLnaBFzqsaM+SWxfrTdClIFDWyADcQ+5jKjeeLmR9PnJOJGjdOI/lvrsLojRKsZ1Ip4on3MCR887Lii+BSPVP3UB+wMA4OK+i7JbDK2wH3BJ5s1iWWzKiMl+BAMx1PpFQ4e/Ey+TpDZ+Pnvdr4X/xoVc83ogs5+3fch5aSt2uPYJVtS4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: jablonski-vce-secrets
      namespace: jablonski
    type: Opaque

