# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
# #    nginx.org/websocket-services: "mousavi-gradio-service"
#     acme.cert-manager.io/http01-edit-in-place: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
#   name: jablonski-vce-app-tls-nginx-ingress
#   namespace: jablonski
# spec:
#   rules:
#   - host: vce-app.pods.uvarc.io
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: jablonski-vce-app-service
#             port:
#               number: 8080
#   tls:
#       - hosts:
#           - vce-app.pods.uvarc.io
#         secretName: jablonski-vce-app-nginx-tls-ingress-secret
