# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     acme.cert-manager.io/http01-edit-in-place: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
#   name: jablonski-vce-app-tls-nginx-ingress
#   namespace: jablonski
# spec:
#   rules:
#     - host: vce-app.pods.uvarc.io
#       http:
#         paths:
#           - backend:
#               serviceName: jablonski-vce-app-service
#               servicePort: 8080
#             path: /
#     #This section is only required if TLS is to be enabled for the Ingress
#   tls:
#       - hosts:
#           - vce-app.pods.uvarc.io
#         secretName: jablonski-vce-app-nginx-tls-ingress-secret
