apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jablonski-mysql-passwords
  namespace: jablonski
spec:
  encryptedData:
    mysql-password: AgBIPkpxpsD/y+qaS0NU49vH/Odbd1wGfEtyKpZ1ziVFfRsLGxXmnvaykiVrffpoZbpP5AiZLZfbbGZDFAceOTuFXQt94UlGhjErvDcjtqCASI6422Ak6cCFXt9R5R+NjjVm9K8HtEgZcUdq15Yp0hvjM7/+uhEqY6G4dDbG/ML5cxuIndtVTcqoPUiPWgPDMs2KgICVvZlpl/ghNm8fq0TR2kkmaJnCfyvu7AeM9lqFogeFqTyL3CB0J2RBXixOuQ8qEuVf909XZwJxyXGUqUJ/MGP0EXIqRUBeg6piyPp9gxoWhcpJc5p3czUHcZwTwtuoDRTs5QexKfKILPafAg2TFFEqVXULjNlBQi5oTuu5NwimhqtzQ/I8qWEOpkqMXfDV7BC5668USgeaKPFdoEylRf1fRPNxScVW1wWSWhFUa3cqwMt3tau8Q9enBD20z6gbpJKHKFrCNpeE8VIvtOdx/S2YRHC9GnuwLDqoQ3HlGq71v41LN7/UH7u67MpbBeq5P3rX8mF91BqJlui7rDBKTVsyho2FiDoBNdRh7fHcOHC7eCcg2VzrFYySStxSs2YxtJQHZ0kQoTMyekW1AA4VQOh7u3WtEJw/jQqqQ1tt+yn71ctDVRVro/jaIEVK0+DkHA8mUvQMBu0mnMSoyao6nlSdkb2BrNIvKJUZbfmR7wmrAxjmnykxxLCn7PgOCIC7EXYMTixcInsamcs=
    mysql-root-password: AgABqmGwkQ7QmDd4+YmgJSsr7Xtn1nAMlQOCcDXrq/e5oojmm8pRWsPtY9L4w8R0B0Ae3nkC7o/R3AC3iy2aGacGnWHzIGmy5SggxcynJfZgcIdw2ElQywx/xu4iISpjWKawvywfNJp2tRCiOUP5EW0R0eCIc+yFXwUEXHg8wLBgjUBIqlqW05SgktrFxv6sjY5NruQGnMv0Q4XiWhIhkolABpKcK6PzIuqTapoNy0lrk9Wp2rO0GmduRPU8LADDAAYmo0gddgJjMLFUcbJiq838wdDlLizCP86dVfFKMVywo629bUMAF7SP2rfMwswWoZaLyRqVNQOEQX2JIOhaHA9Dgdz22lDUWnW5t3z+XUxCkPYGxrlpaqDptqQl5FpIBxDGRGdfZ0GrUk9e2UsPfDyGgNaB+ypRaL8DkLW9eV+XE9nx9VDyEWSLeiFDUzSd8ZtWerKM7X2waTPSDoqGpI+M6I1bQ9NDuPzEibETOmc/lv9noV+yL8l1qUNRaEusdMPVCJYV8heueASnggdFiT1AYsoOnDvqiSguelcH0CNVjDIrLv04d0nN/Rq0fZR8j/ovcF3r+GjUTMTbrvbe7IpcfJylmmNXsG+6bAKIsQkRj0BdJqhMkYjPHbLrVAh5f8Ximp8C5pwfx1mRdjDxgozlOcnbaWwW/WfzCT4DVVSaygGVe+huSn8Avd+z4MObEAQhBAXJUUuG1QCu7K4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: jablonski-mysql-passwords
      namespace: jablonski
    type: Opaque

