apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jablonski-vce-app-editor2-nfs-pvc
  namespace: jablonski
spec:
  storageClassName: jablonski-vce-app-editor2-sc
  accessModes:
    - ReadOnlyMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
