# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.org/websocket-services: "jablonski-vce-app-editor2-service"
#   name: jablonski-vce-app-editor2-nginx-ingress
#   namespace: jablonski
# spec:
#   rules:
#     - host: 	vce-app-ed.pods.uvarc.io
#       http:
#         paths:
#           - backend:
#               serviceName: jablonski-vce-app-editor2-service
#               servicePort: 8080
#             path: /
